name: Build, Test (explicit Unit project)

on:
  push:
    branches:
      - testing/**
      - main
      - '**'    # allow manual branch runs; remove if too noisy
  pull_request:
    branches:
      - testing/**
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build App (Release)
        run: dotnet build src/App/App.csproj -c Release --no-restore

      - name: Run Unit tests (explicit)
        run: dotnet test tests/Unit/Unit.csproj -c Release --no-build --verbosity normal
        shell: pwsh
