name: CI Tests (override)

on:
  push:
    branches: [ testing/** ]
  pull_request:
    branches: [ testing/** ]

jobs:
  unit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build App (Release)
        run: dotnet build src/App/App.csproj -c Release --no-restore
      - name: Test Unit (explicit project)
        run: dotnet test tests/Unit/Unit.csproj -c Release --no-build --verbosity normal
