name: CI — explicit Build & Test (Windows)

on:
  push:
    branches:
      - 'testing/**'
      - 'testing/v1.0.0'
  pull_request:
    branches:
      - 'testing/**'
      - 'testing/v1.0.0'

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore, Build and Test (explicit)
        shell: pwsh
        run: |
          # find a solution file (search repo) and fail clearly if none found
          $sln = (Get-ChildItem -Path . -Recurse -Filter *.sln -ErrorAction SilentlyContinue | Select-Object -First 1).FullName
          if (-not $sln) { Write-Error "No .sln found in repo; please locate your solution file."; exit 1 }
          Write-Host "Using solution: $sln"

          dotnet restore $sln
          dotnet build $sln -c Release --no-restore

          # find the Unit test project explicitly (prefer tests/Unit/Unit.csproj)
          $testproj = (Get-ChildItem -Path . -Recurse -Filter 'Unit.csproj' -ErrorAction SilentlyContinue | Select-Object -First 1).FullName
          if (-not $testproj) {
            $testproj = (Get-ChildItem -Path . -Recurse -Filter '*Tests.csproj' -ErrorAction SilentlyContinue | Select-Object -First 1).FullName
          }
          if (-not $testproj) { Write-Error "No test project (Unit.csproj or *Tests.csproj) found."; exit 1 }
          Write-Host "Testing project: $testproj"

          dotnet test $testproj -c Release --no-build --verbosity normal
