name: CI

on:
  push:
    branches:
      - 'testing/**'
  pull_request:
    branches:
      - 'testing/**'

jobs:
  build:
    name: Build, Test & Format (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore all projects
        shell: pwsh
        run: |
          $csprojs = Get-ChildItem -Path . -Filter *.csproj -Recurse -ErrorAction SilentlyContinue
          if ($csprojs.Count -eq 0) {
            Write-Error "No .csproj files found in repo; aborting restore."
            exit 1
          }
          foreach ($p in $csprojs) {
            Write-Output "Restoring $($p.FullName)"
            dotnet restore $p.FullName
          }

      - name: Install dotnet-format (local tool)
        shell: pwsh
        run: |
          dotnet tool install --tool-path ./.dotnet-tools dotnet-format --version 8.0.0 || true
          $fmtExe = Join-Path $PWD '.dotnet-tools/dotnet-format.exe'
          if (-not (Test-Path $fmtExe)) { $fmtExe = Join-Path $PWD '.dotnet-tools/dotnet-format' }
          Write-Output "dotnet-format = $fmtExe"
          if (-not (Test-Path $fmtExe)) { Write-Warning "dotnet-format not found at $fmtExe; formatting steps may fail." }

      - name: Verify formatting (fail if repo not formatted)
        shell: pwsh
        run: |
          $fmtExe = Join-Path $PWD '.dotnet-tools/dotnet-format.exe'
          if (-not (Test-Path $fmtExe)) { $fmtExe = Join-Path $PWD '.dotnet-tools/dotnet-format' }
          if (Test-Path $fmtExe) {
            & $fmtExe --verify-no-changes --severity info
          } else {
            Write-Output "Skipping dotnet-format verify because tool wasn't installed."
          }

      - name: Build (all solutions or projects)
        shell: pwsh
        run: |
          $slns = Get-ChildItem -Path . -Filter *.sln -Recurse -ErrorAction SilentlyContinue
          if ($slns.Count -gt 0) {
            foreach ($s in $slns) {
              Write-Output "Building solution $($s.FullName)"
              dotnet build $s.FullName -c Release
            }
          } else {
            $cs = Get-ChildItem -Path . -Filter *.csproj -Recurse
            foreach ($c in $cs) {
              Write-Output "Building project $($c.FullName)"
              dotnet build $c.FullName -c Release
            }
          }

      - name: Run tests (detect test projects)
        shell: pwsh
        run: |
          $tests = Get-ChildItem -Path . -Recurse -Filter '*Tests.csproj' -ErrorAction SilentlyContinue
          if ($tests.Count -eq 0) { $tests = Get-ChildItem -Path . -Recurse -Filter '*.Tests.csproj' -ErrorAction SilentlyContinue }
          if ($tests.Count -eq 0) {
            Write-Output "No explicit test project matches found. Running 'dotnet test' for all projects."
            dotnet test --verbosity normal
          } else {
            foreach ($t in $tests) {
              Write-Output "Testing $($t.FullName)"
              dotnet test $t.FullName -c Release --no-build --verbosity normal
            }
          }

  format-diff:
    name: Create format diff (when format fails)
    runs-on: windows-latest
    needs: build
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-format (local)
        shell: pwsh
        run: |
          dotnet tool install --tool-path ./.dotnet-tools dotnet-format --version 8.0.0 || true

      - name: Run dotnet format and create diff
        shell: pwsh
        run: |
          $fmtExe = Join-Path $PWD '.dotnet-tools/dotnet-format.exe'
          if (-not (Test-Path $fmtExe)) { $fmtExe = Join-Path $PWD '.dotnet-tools/dotnet-format' }
          if (Test-Path $fmtExe) {
            & $fmtExe --verbosity diagnostic || true
          } else {
            Write-Output "dotnet-format not found; skipping auto-format."
          }
          git --no-pager diff > format-diff.patch || true

      - name: Upload format-diff
        uses: actions/upload-artifact@v4
        with:
          name: format-diff
          path: format-diff.patch
