name: windows-build
on:
  push:
    branches: [ "testing/v1.0.0" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: No-op
        run: |
          echo CI skeleton for testing branch
